name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Lint deploy.sh script
        run: |
          shellcheck -e SC1091 deploy.sh

      - name: Make deploy.sh executable
        run: chmod +x deploy.sh

      - name: Run deploy.sh (build, load, and package)
        run: sudo bash deploy.sh

      - name: Check for makeself installer
        id: check_makeself
        run: |
          if [ -f hello-world-installer.run ]; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload makeself installer artifact
        if: steps.check_makeself.outputs.found == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-installer
          path: hello-world-installer.run 